apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka2
  name: kafka2
spec:
  type: LoadBalancer
  ports:
    - name: "29092"
      port: 29092
      targetPort: 29092
    - name: "9092"
      port: 9092
      targetPort: 9092
  externalIPs:
    - 192.168.56.62
  selector:
    io.kompose.service: kafka2