apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka3
  name: kafka3
spec:
  type: LoadBalancer
  ports:
    - name: "29093"
      port: 29093
      targetPort: 29093
    - name: "9093"
      port: 9093
      targetPort: 9093
  externalIPs:
    - 192.168.56.63
  selector:
    io.kompose.service: kafka3