apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka1
  name: kafka1
spec:
  type: LoadBalancer
  ports:
    - name: "19091"
      port: 19091
      targetPort: 19091
    - name: "9091"
      port: 9091
      targetPort: 9091
  externalIPs:
    - 192.168.56.61
  selector:
    io.kompose.service: kafka1