apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-dags-folder
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  local:
    path: /home/mhtuan/work/k8s-kafka/airflow/dags
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-node
  
  # hostPath:
  #   path: "/home/mhtuan/work/k8s-kafka/airflow/dags"
