apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-dags-folder
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi