apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka2
  name: kafka2
spec:
  type: NodePort
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
      nodePort: 30002
  selector:
    io.kompose.service: kafka2
