apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka3
  name: kafka3
spec:
  type: NodePort
  ports:
    - name: "9093"
      port: 9093
      targetPort: 9093
      nodePort: 30003
  selector:
    io.kompose.service: kafka3
