apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafka1
  name: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/test-multi-broker-default: "true"
        io.kompose.service: kafka1
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - "worker-node"
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://192.168.56.61:9091
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: LISTENER_DOCKER_INTERNAL
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: confluentinc/cp-kafka:5.3.0
          name: kafka-broker-1
          ports:
            - containerPort: 9091
              hostPort: 9091
              protocol: TCP
            - containerPort: 19091
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka1-claim0
      hostname: kafka1
      restartPolicy: Always
      volumes:
        - name: kafka1-claim0
          persistentVolumeClaim:
            claimName: kafka1-claim0