apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafka3
  name: kafka3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/test-multi-broker-default: "true"
        io.kompose.service: kafka3
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - "worker-node-3"
      containers:
        - env:
            - name: KAFKA_LISTENERS
              value: LISTENER_DOCKER_INTERNAL://:29093,LISTENER_DOCKER_EXTERNAL://:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: LISTENER_DOCKER_INTERNAL://kafka3:29093,LISTENER_DOCKER_EXTERNAL://192.168.56.63:9093
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: LISTENER_DOCKER_INTERNAL
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: confluentinc/cp-kafka:5.3.0
          name: kafka-broker-3
          ports:
            - containerPort: 29093
            - containerPort: 9093
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka3-claim0
      hostname: kafka3
      restartPolicy: Always
      volumes:
        - name: kafka3-claim0
          persistentVolumeClaim:
            claimName: kafka3-claim0